name: PullRequest
on:
  pull_request:
    brached: ["main"]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18

      - name: Check out code
        uses: actions/checkout@v2

      - name: Check fmt
        run: .github/workflows/check_fmt.sh
